### ISSUE TITLE
No named parameter with the name 'selectedIndex'

### ISSUE THREAD

**Issue by mohit67890** [pedromassango/bottom_navy_bar#10]
Hey, I'm getting this error.
Error: No named parameter with the name 'selectedIndex'.
          selectedIndex: _index,
Context: Found this candidate, but the arguments don't match.
  BottomNavyBar(
  ^

**Comment by pedromassango** [comment]
I just solved it. Please use `selectedIndex ` property instead.

**Comment by vanlooverenkoen** [comment]
Update the readme to make it more clear this is no longer available
