### ISSUE TITLE
Shadow box cannot be disabled

### ISSUE THREAD

**Issue by FACOLOMBANI** [pedromassango/bottom_navy_bar#11]
Hi

Is it possible to add an option to disable the shadow box line 109?

Regards.

**Comment by pedromassango** [comment]
Thanks I just added this option, set `showElevation` to false in the BottomNavBar to remove the elevation

**Comment by pedromassango** [comment]
Added here: https://github.com/pedromassango/bottom_navy_bar/commit/663fb8431254596488b6e1a022992593d0cdac64
