### ISSUE TITLE
Getting an error with iOS build

### ISSUE THREAD

**Issue by codoffer** [pedromassango/bottom_navy_bar#115]
**Flutter**
Flutter 3.22.0-36.0.pre.48 • channel master • https://github.com/flutter/flutter.git
Framework • revision adc9307bc5 (8 days ago) • 2024-05-18 01:04:30 -0400
Engine • revision 552a965b70
Tools • Dart 3.5.0 (build 3.5.0-167.0.dev) • DevTools 2.36.0-dev.10

**pubspec.yaml**
bottom_navy_bar: ^6.0.0

**Error**
Failed to build iOS app
Error (Xcode): ../../.pub-cache/hosted/pub.dev/bottom_navy_bar-6.0.0/lib/bottom_navy_bar.dart:68:58: Error: The getter
'bottomAppBarColor' isn't defined for the class 'ThemeData'.

**Comment by Marwa-elsherif** [comment]
I have the same error after searching I found that "  bottomAppBarColor "  is not provided so i replaced it by 
 " bottomAppBarTheme.color " and don't forget to make the backgroundColor type is Color? instead of Color 
I tried that and it works .

**Comment by Marwa-elsherif** [comment]
I have the same error. After searching, I found that `bottomAppBarColor` is not provided, so I replaced it with `bottomAppBarTheme.color`. Also, don't forget to change the `backgroundColor` type to `Color?` instead of `Color`. I tried that, and it works.

**Comment by codoffer** [comment]
@Marwa-elsherif  Thanks for your reply. We have used an alternative package - https://pub.dev/packages/salomon_bottom_bar

**Comment by fibau** [comment]
@Marwa-elsherif where to replace bottomAppBarColor? I can't find it anywhere.

**Comment by Marwa-elsherif** [comment]
it's at line number 68, you can also searching about it using ' Ctrl+ f ' then type  ' bottomAppBarColor ' in the search field (that in case of using VS code)

**Comment by antonio-pedro99** [comment]
> **Flutter** Flutter 3.22.0-36.0.pre.48 • channel master • https://github.com/flutter/flutter.git Framework • revision adc9307bc5 (8 days ago) • 2024-05-18 01:04:30 -0400 Engine • revision 552a965b70 Tools • Dart 3.5.0 (build 3.5.0-167.0.dev) • DevTools 2.36.0-dev.10
> 
> **pubspec.yaml** bottom_navy_bar: ^6.0.0
> 
> **Error** Failed to build iOS app Error (Xcode): ../../.pub-cache/hosted/pub.dev/bottom_navy_bar-6.0.0/lib/bottom_navy_bar.dart:68:58: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.

This has been fixed by #109 , recent update will be available soon
