### ISSUE TITLE
The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.

### ISSUE THREAD

**Issue by 6Yolo6** [pedromassango/bottom_navy_bar#116]
flutter run

/C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bottom_navy_bar-6.0.0/lib/bottom_navy_bar.dart:68:58: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.
 - 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/E:/flutterSDK3.19.3/flutter/packages/flutter/lib/src/material/theme_data.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'bottomAppBarColor'.
    final bgColor = backgroundColor ?? Theme.of(context).bottomAppBarColor;
                                                         ^^^^^^^^^^^^^^^^^
ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

**Comment by sergedawg** [comment]
same issue here

**Comment by antonio-pedro99** [comment]
> flutter run
> 
> /C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bottom_navy_bar-6.0.0/lib/bottom_navy_bar.dart:68:58: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.
> 
> * 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/E:/flutterSDK3.19.3/flutter/packages/flutter/lib/src/material/theme_data.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named 'bottomAppBarColor'.
>   final bgColor = backgroundColor ?? Theme.of(context).bottomAppBarColor;
>   ^^^^^^^^^^^^^^^^^
>   ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
>   ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
>   Target kernel_snapshot failed: Exception
> 
> FAILURE: Build failed with an exception.

This is because `bottomAppBarColor` is deprecated in the recent flutter version.

**Comment by antonio-pedro99** [comment]
> flutter run
> 
> /C:/Users/ASUS/AppData/Local/Pub/Cache/hosted/pub.flutter-io.cn/bottom_navy_bar-6.0.0/lib/bottom_navy_bar.dart:68:58: Error: The getter 'bottomAppBarColor' isn't defined for the class 'ThemeData'.
> 
> * 'ThemeData' is from 'package:flutter/src/material/theme_data.dart' ('/E:/flutterSDK3.19.3/flutter/packages/flutter/lib/src/material/theme_data.dart').
>   Try correcting the name to the name of an existing getter, or defining a getter or field named 'bottomAppBarColor'.
>   final bgColor = backgroundColor ?? Theme.of(context).bottomAppBarColor;
>   ^^^^^^^^^^^^^^^^^
>   ע: ĳЩ�����ļ�ʹ�û򸲸����ѹ�ʱ�� API��
>   ע: �й���ϸ��Ϣ, ��ʹ�� -Xlint:deprecation ���±��롣
>   Target kernel_snapshot failed: Exception
> 
> FAILURE: Build failed with an exception.

This has been fixed by #109 , recent update will be available soon
