### ISSUE TITLE
Bar is to low at iPhone X(s/R)

### ISSUE THREAD

**Issue by kay4ik** [pedromassango/bottom_navy_bar#13]
At the Bottom of the iPhone X... is the Navigation "Line". At this point there should be white space. The Navy Bar is behind this Line.

![image](https://user-images.githubusercontent.com/33052782/59437467-f34c2800-8df1-11e9-8a90-99726fefb90a.png)

How it should look:

![image](https://user-images.githubusercontent.com/33052782/59437709-5b9b0980-8df2-11e9-845a-74118390fed7.png)

**Comment by pedromassango** [comment]
Hi, can you try please too wrap the BottomNavyBar with a SafeArea widget? I don't have a Mac to try it. Thank you

**Comment by kay4ik** [comment]
Hey,
it nearly works..

![image](https://user-images.githubusercontent.com/33052782/59513250-c0219b80-8eba-11e9-90f6-9b6bded113de.png)

But do you know how tho change the Background to white below the SafeArea?

**Comment by pedromassango** [comment]
Great. Thank you for this @kay4ik. Maybe you want to make a pull request with this contribuition?!

Or I can just do it by my self. Thanks

**Comment by pedromassango** [comment]
Fixed since this version: `5.0.0`
