### ISSUE TITLE
Assert in Constructor

### ISSUE THREAD

**Issue by emallay** [pedromassango/bottom_navy_bar#14]
Thanks for posting your code. Nice stuff!

For line 24 in the constructor, there is the following assert:

`assert(items.length >= 2 || items.length >= 5);`

Shouldn't it be:

`assert(items.length >= 2 && items.length <= 5);`

As it stands, an items.length of 7 (for ex) would pass the test contrary to the requirements listed in your docs.

**Comment by pedromassango** [comment]
Fixed on this commit: https://github.com/pedromassango/bottom_navy_bar/commit/a278217a66948c2e316f88a81ba002ad0af7cd87. Thank you!
