### ISSUE TITLE
While Sliding the page, Nav Button is not updated ?

### ISSUE THREAD

**Issue by StrangeNoob** [pedromassango/bottom_navy_bar#16]
While Slide between the Container, Nav Button animate doesnt change according to widget
![device-2019-06-28-191101](https://user-images.githubusercontent.com/42904343/60346532-f261eb80-99d8-11e9-9bd5-f042444cb111.gif)

**Comment by pedromassango** [comment]
Thanks @StrangeNoob.

Can you please elaborate your problem? I will close this for now. Feel free to re-open it later

**Comment by JaysusM** [comment]
Hi, I have the same problem using this. The problem is when you swipe to the next screen the navbar doesn't update its selectedIndex (as you can see in @StrangeNoob gif), is this a bug or should I use an actionListener in pageController?
Thank you in advance!

**Comment by pedromassango** [comment]
Can you please show me the code that update the selectedIndex when sliding between pages

**Comment by JaysusM** [comment]
Hi @pedromassango , https://github.com/JaysusM/NBA-Go/blob/master/lib/ui/app_scaffold.dart in that widget is where I am having the problem.

**Comment by pedromassango** [comment]
The problem is that your are not updating the selectedIndex after swipe PageView. You must attach a listener to PageViewController to get updated when the pageView change

**Comment by JaysusM** [comment]
How should I implement it, could you please post an example code and/or update the README with that code, it would be very useful. If I use a listener, it will check every change include when I tap the navbar button, and that looks horrible. 
This is what I tried:
`this._pageController.addListener(() {
      this.setState(() {
        this._currentIndex = this._pageController.page.truncate();
      });
    });`
