### ISSUE TITLE
Error selectedIndex

### ISSUE THREAD

**Issue by malikdoksoz** [pedromassango/bottom_navy_bar#18]
```
BottomNavyBar(
   selectedIndex: _selectedIndex,
   showElevation: true, // use this to remove appBar's elevation
   onItemSelected: (index) => setState(() {
              _selectedIndex = index;
              _pageController.animateToPage(index,
                  duration: Duration(milliseconds: 300), curve: Curves.ease);
    }),
```
BottomNavyBar has a currentIndex not selectedIndex.
**bottom_navy_bar: ^3.0.0**
Flutter 1.7.8

**Comment by pedromassango** [comment]
Thanks @malikdoksoz. Use `selectedIndex` to update the current index.

**Comment by Sarmed-armis** [comment]
hey this is still not work 

 bottom_navy_bar: ^3.0.0 

error is selectedIndex parameter is not define

**Comment by pedromassango** [comment]
@Sarmed-armis please use the latest version that is currently on: `5.3.2`
