### ISSUE TITLE
Throwing error at 'currentIndex' when upgraded flutter from 2.1.0 to 2.3.0

### ISSUE THREAD

**Issue by tusharspol** [pedromassango/bottom_navy_bar#23]
I upgraded my flutter from 2.1.0 to 2.3.0 and suddenly it started to throw me an error i.e. 

> Error: No named parameter with the name 'currentIndex'.

I'm currently on 5.1.0.

**Comment by pedromassango** [comment]
Please use `selectedIndex`

**Comment by tusharspol** [comment]
> Please use `selectedIndex`

Yess ! It's working now. It started working when I restarted VSCode.
