### ISSUE TITLE
Single item opacity

### ISSUE THREAD

**Issue by aleksandar-radivojevic** [pedromassango/bottom_navy_bar#26]
Is there any way to control single bottom navy item opacity?

**Comment by aleksandar-radivojevic** [comment]
Because I want to archive design similar to this

[https://dribbble.com/shots/6855918-Chili-Labs-App](url)

**Comment by omishah** [comment]
have you tried playing with **activeColor** and  **inactiveColor** ? I guess that can fulfill your needs.

**Comment by pedromassango** [comment]
As suggested you can play with the colors. I'm closing this for now. feel free to re-open if neccessary

**Comment by mjarpitanand** [comment]
I want to achieve same thing as @aleksandar-radivojevic  requested., is it done by you, can share code.

**Comment by omishah** [comment]
> I want to achieve same thing as @aleksandar-radivojevic requested., is it done by you, can share code.

are you still looking for a solution?
