### ISSUE TITLE
[Q] I have 2 items, how to center it?

### ISSUE THREAD

**Issue by nguyenhuutinh** [pedromassango/bottom_navy_bar#31]
hello,
thanks for your plugin.
My question is : I have 2 items, how to center it?

Thanks

**Comment by nguyenhuutinh** [comment]
<img width="367" alt="Screenshot 2019-11-04 at 11 00 02 PM" src="https://user-images.githubusercontent.com/4114159/68130754-deb22d00-ff56-11e9-9348-41263067a085.png">

**Comment by georgeherby** [comment]
Looks like this is not possible currently. It could be added as a config option via PR/change

It currently uses `MainAxisAlignment.spaceBetween` if it was a config you could use `center` or `spaceAround`

https://github.com/pedromassango/bottom_navy_bar/blob/master/lib/bottom_navy_bar.dart#L97

**Comment by georgeherby** [comment]
#33

**Comment by georgeherby** [comment]
@nguyenhuutinh See #33

**Comment by pedromassango** [comment]
Hey @georgeherby I'm waiting your conflicts to close this issue in the #33

**Comment by georgeherby** [comment]
All done @pedromassango
