### ISSUE TITLE
This package does work with Flutter Web!  

### ISSUE THREAD

**Issue by Jeremywhiteley** [pedromassango/bottom_navy_bar#36]
This package is working very well with Flutter Web.  You should add that it works with Flutter web!

**Comment by pedromassango** [comment]
Yes. It is just a normal Flutter package.

**Comment by juanagu** [comment]
Hi, @pedromassango  Do you have a plan to support the web? Thanks!

**Comment by Jeremywhiteley** [comment]
> Hi, @pedromassango Do you have a plan to support the web? Thanks!

It works with Flutter Web very well.   I use it in my app.  No issues at all.
