### ISSUE TITLE
Can't set default active item before Tap

### ISSUE THREAD

**Issue by Shakle** [pedromassango/bottom_navy_bar#4]
I'd like to have an item(Tab) to be selected on the first launch, but it only reacts to a tap.
index is 0 by default, but it awaits for a tap, all tabs have inactive view by default.

**Comment by pedromassango** [comment]
Thank you. I'm working on it

**Comment by pedromassango** [comment]
Fixed on this commit: https://github.com/pedromassango/bottom_navy_bar/commit/8726c5757ffd146697695db988af09b8f2d53c3d Thank you.

**Comment by Shakle** [comment]
Thank you, would be very appreciated if you can fix it soon, we are going to use it in our app that will be released in a week)

Good bottom bat, thanks)

[Изображение]


________________________________

**Comment by Shakle** [comment]
Ah, you've already done it, wonderful)
________________________________
