### ISSUE TITLE
ImageIcon

### ISSUE THREAD

**Issue by fabioselau077** [pedromassango/bottom_navy_bar#43]
Hello, as my icons are customized I can only access using icon: ImageIcon(images/ icon.png), in BottomNavigationBarItem I can, but in your package only accept Icon in icon (icon: Icon(Icons.add)
How to solve?

**Comment by pedromassango** [comment]
Yes. Sorry about that, it must change in the next releases. For now you can convert your .png images into IconData to be used inside icon using some tools. Please refer to this post:[https://medium.com/flutterpub/how-to-use-custom-icons-in-flutter-834a079d977] to learn how.

**Comment by fabioselau077** [comment]
> Yes. Sorry about that, it must change in the next releases. For now you can convert your .png images into IconData to be used inside icon using some tools. Please refer to this post:https://medium.com/flutterpub/how-to-use-custom-icons-in-flutter-834a079d977 to learn how.

Thanks brother. Amazing package, thanks for sharing.
