### ISSUE TITLE
Can we use bottom navy bar on top instead?

### ISSUE THREAD

**Issue by djaygit** [pedromassango/bottom_navy_bar#46]
i'm still new to flutter and was wonder if i can use it on the top instead of bottom?

**Comment by pedromassango** [comment]
Since this package is just a widget, yes you can use it anywhere.

**Comment by djaygit** [comment]
how to i use it on the top? thanks

**Comment by pedromassango** [comment]
What do yoy mean on top?

**Comment by djaygit** [comment]
as a navigation bar....
![image](https://user-images.githubusercontent.com/1255841/75321396-ae402700-5896-11ea-975d-df93df7537b5.png)

**Comment by pedromassango** [comment]
Yes, you can. It is just a Widget, you can add it everywhere
