### ISSUE TITLE
Is it possible to programmatically change the bottom nav position?

### ISSUE THREAD

**Issue by papakay** [pedromassango/bottom_navy_bar#5]
Hi, I really commend the great work put into this package.

Please I would like to know if it's possible to programmatically change the position of the tab. 

For instance, I want to be able to transition the user to another page without them clicking on the bottom navigation bar.

Thanks.

**Comment by pedromassango** [comment]
Yes it it possible, just use the ** currentIndex** property to change it programmatically. Thank you!
