### ISSUE TITLE
Adding Tooltip to BottomNavyBar.items

### ISSUE THREAD

**Issue by sterrenb** [pedromassango/bottom_navy_bar#50]
Hello, I would like to add a [`Tooltip`](https://api.flutter.dev/flutter/material/Tooltip-class.html) to every item in `BottomNavyBar.items`.

Currently, the items cannot easily be wrapped in a `Tooltip` since `BottomNavyBar.items` has the explicit type `List<BottomNavyBarItem>`.

Ideally, I think `BottomNavyBar.items` should be of type `List<Widget>` instead. Then, the `BottomNavyBarItem`s can be wrapped with other Widgets without impacting the interface.

This works well in existing native Widgets, for example `IconButton`. `IconButton.icon` is typically an `Icon`, but the interface specifies `Widget`.

What are your thoughts on using the generic `Widget` type in this case?

**Comment by pedromassango** [comment]
I will probably work on this in January when I will have more free time.
