### ISSUE TITLE
currentIndex

### ISSUE THREAD

**Issue by peterramsis** [pedromassango/bottom_navy_bar#51]
in first time tab not active

**Comment by pedromassango** [comment]
I thanks for opening this issue. Can you please show me your implementation of this package?

**Comment by peterramsis** [comment]
import 'package:coronavirus/Pages/About_screen.dart';
import 'package:coronavirus/Pages/Data_Api.dart';
import 'package:flutter/material.dart';
import 'package:bottom_navy_bar/bottom_navy_bar.dart';
import 'package:dio/dio.dart';
import 'package:flutter_spinkit/flutter_spinkit.dart';
class Home_page extends StatefulWidget {
  @override
  _Home_pageState createState() => _Home_pageState();
}

class _Home_pageState extends State<Home_page> {
  Map data = {};
  bool is_loading = true;
  List<String> title_App = ["Global Coronavirus information","Countries","About"];

  int _currentIndex = 1;
  PageController _pageController;

  @override

  String type_data = "all"; // get information depend this variable

  @override
  void dispose() {
    _pageController.dispose();
    super.dispose();
  }

  @override
  void initState() {
    super.initState();
    _pageController = PageController();

  }

  void _onItemTapped(int index) {
    setState(() {
      _currentIndex = index;
    });
  }





  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: Colors.white12,
      appBar: AppBar(
        title: Text("${title_App[_currentIndex]}",
        style:TextStyle(
          fontSize: 17
        ),),
        backgroundColor: Colors.black45,
      ),
        body: SizedBox.expand(
          child: PageView(
            controller: _pageController,
            onPageChanged: (index) {
              setState(() => _currentIndex = index);
            },
            children: <Widget>[
            Container(
           child:Text("page one");
            ),
Container(
           child:Text("page two");
            ),
Container(
           child:Text("page three");
            ),
         
            ],
          ),
        )
        ,
        bottomNavigationBar: BottomNavyBar(
          backgroundColor: Colors.white12,
          currentIndex: _currentIndex,
          onItemSelected: (index){

            setState(() {
              _currentIndex = index;
              _pageController.animateToPage(index,
                  duration: Duration(milliseconds: 300), curve: Curves.ease);
            });


            if(index == 0){
              getData();
            }
          },
          items: [
            BottomNavyBarItem(
              icon: Icon(Icons.language),
              title: Text('Global'),
                activeColor: Colors.white,
                 inactiveColor: Color(0xFFa20018)
            ),
            BottomNavyBarItem(
                icon: Icon(Icons.flag),
                title: Text('Countries'),
                activeColor: Colors.white,
                 inactiveColor: Color(0xFFa20018)
            ),
            BottomNavyBarItem(
                icon: Icon(Icons.info),
                title: Text('About'),
                activeColor: Colors.white,
                inactiveColor: Color(0xFFa20018)
            ),
          ],
        )
    );
  }
}

**Comment by MaximeAubanel** [comment]
I think he is talking when you set _currentIndex to 1, the bottom navigation is at the right index but the first tab is not set. You need to manually do ` _pageController.jumpToPage(_currentIndex);` in your widget build to make it active.
