### ISSUE TITLE
Item Max

### ISSUE THREAD

**Issue by alfaben12** [pedromassango/bottom_navy_bar#62]
BottomNavyBarItem max is 5, how to use more than 5 item?

**Comment by pedromassango** [comment]
Currently it is not possible.

It is recommended to have no more than five items in your navigation bar!

**Comment by alfaben12** [comment]
I think many people need that, I'm still waiting for an update.

I'ts a great library

**Comment by pedromassango** [comment]
I don't think I will work on this as this break the specs of a bottom navigation bar.
