### ISSUE TITLE
Disable Swiping Right or Left

### ISSUE THREAD

**Issue by Moaminv** [pedromassango/bottom_navy_bar#63]
Hello. Is it possible to disable Swiping Right or Left? I only want to switch between screens by clicking on the bottom navy bar icons, Not Swiping pages right or left

I really appreciate your work, Nice bottom_navy_bar 👍

**Comment by pedromassango** [comment]
Hi, Thank you.

The page swipe feature is not part of this library, so if you don't implement it in your project this package will not add it for you.

I will close this for now. Feel free to leave a comment if necessary.

**Comment by Moaminv** [comment]
Sorry I'm new to flutter, But if "swipe feature is not part of this library". 
How we're able to swipe pages like here in the middle of the screen:
![fix](https://user-images.githubusercontent.com/51845593/88303192-53bdd080-cd39-11ea-93c7-d0f1ef425f23.gif)

I would like to go from page to page by clicking on the bottom navy bar item only

**Comment by Moaminv** [comment]
Thank you. You were right. I fixed it by writing this code to PageView: 
`PageView(physics:new NeverScrollableScrollPhysics())`

`body: PageView(
              physics: NeverScrollableScrollPhysics(),
              controller: _pageController,
              onPageChanged: (int index) {
                setState(() => _currentIndex = index);
              },
              children: <Widget>[
                chooseCountry(),
                Profile(),
              ],
            ),
            bottomNavigationBar: BottomNavyBar(
              iconSize: 28,
              containerHeight: 70,
              backgroundColor: const Color(0xFFFFFFFF),
              itemCornerRadius: 5,
              curve: Curves.easeInBack,
              selectedIndex: _currentIndex,
              onItemSelected: (int index) => setState(() {
                _currentIndex = index;
                _pageController.animateToPage(index,
                    duration: const Duration(milliseconds: 100),
                    curve: Curves.ease);
              }),`
