### ISSUE TITLE
showing inactive items's title

### ISSUE THREAD

**Issue by alkaffdt** [pedromassango/bottom_navy_bar#68]
can we make inactive item's title appear ?

**Comment by pedromassango** [comment]
Currently this is not possible in the current version of the package but would be a great addition.

**Comment by MustafaAdam** [comment]
This would be a lovely addition. Only an icon showing isn't as useful and clear as title plus icon when the item is inactive.

**Comment by satyajitghana** [comment]
Seems like the official `BottomNavigationBar` is a good alternative

**Comment by devMappouras** [comment]
Hey, after 2 years did we implement this? it would be great to have the option to show inactive items title. Since showing the names of the buttons follows the Heuristic evaluation

**Comment by antonio-pedro99** [comment]
hey @devMappouras do you want to work on this?

**Comment by agam1092005** [comment]
@antonio-pedro99, Can you assign this issue to me ?

**Comment by agam1092005** [comment]
Kindly check & merge the PR

**Comment by antonio-pedro99** [comment]
Thanks again @agam1092005.

**Comment by antonio-pedro99** [comment]
@pedromassango can you take a Quick look at this?

**Comment by antonio-pedro99** [comment]
This has been fixed by #114
