### ISSUE TITLE
Swiping through pages work but Changing page through nav bar doesnt bar

### ISSUE THREAD

**Issue by prateekmedia** [pedromassango/bottom_navy_bar#73]
Below is the code in my main.dart file, note that swiping behaviour works but the logic of pageController doesn't work.
```
class _MyHomePageState extends State<MyHomePage> {
  int _currentIndex = 0;
  PageController _pageController;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: PageView(
          controller: _pageController,
          children: <Widget>[
            HomeContent(),
            CalendarContent(),
            AddContent(),
            ProjectsContent(),
            SettingsContent()
          ],
          onPageChanged: (index) {
            setState(() {
              _currentIndex = index;
            });
          },
        ),
      ),
      bottomNavigationBar: BottomNavyBar(
        selectedIndex: _currentIndex,
        showElevation: true,
        itemCornerRadius: 24,
        curve: Curves.elasticInOut,
        onItemSelected: (index) => setState(() {
          _currentIndex = index;
          _pageController.animateToPage(index,
              duration: Duration(milliseconds: 300), curve: Curves.ease);
        }),
        items: [
          BottomNavyBarItem(
            icon: Icon(Icons.home),
            title: Text('Home'),
            activeColor: Colors.deepPurple[800],
            inactiveColor: Colors.black45
          ),
          BottomNavyBarItem(
            icon: Icon(Icons.calendar_today_outlined),
            title: Text('Calendar'),
            activeColor: Colors.deepPurple[800],
            inactiveColor: Colors.black45
          ),
          BottomNavyBarItem(
            icon: Icon(Icons.add),
            title: Text('Add'),
            activeColor: Colors.deepPurple[800],
            inactiveColor: Colors.black45
          ),
          BottomNavyBarItem(
            icon: Icon(Icons.work_outline_outlined),
            title: Text('Projects'),
            activeColor: Colors.deepPurple[800],
            inactiveColor: Colors.black45
          ),
          BottomNavyBarItem(
            icon: Icon(Icons.settings),
            title: Text('Settings'),
            activeColor: Colors.deepPurple[800],
            inactiveColor: Colors.black45
          ),
        ],
      )
    );
  }
}
```

I tried with both page Controller Jump to page and the animateToPage but it either disables clicking on the items or it doesnt change page and just clicking behaviour works and not page changing one.

Also I tried with and without SizedBox.expand as parent of Page View but it didn't work.

I will try to make a new project and try it again to see if its this package problem or not.

**Comment by prateekmedia** [comment]
Additional Info in pubspec yaml file
```
dependencies:
  flutter:
    sdk: flutter

  carousel_slider: ^2.3.1
  bottom_navy_bar: ^5.6.0
```

**Comment by prateekmedia** [comment]
https://user-images.githubusercontent.com/41370460/103173403-cdc22a80-4880-11eb-8f7b-2b7fa22f4193.mp4

Above is the issue with this code and I was Clicking really hard on the Buttons

**Comment by prateekmedia** [comment]
https://user-images.githubusercontent.com/41370460/103173595-044c7500-4882-11eb-8e80-0565c9f88f6b.mp4

This is other clip in which everything in pageView is working button clicking on Bottom Nav Bar doesnt seem to work

**Comment by prateekmedia** [comment]
I removed pageController and page view that were causing problem and added Widget[_currentIndex] as Children to temporarily fix this issue.

**Comment by pedromassango** [comment]
Hi @prateekmedia 
Are you still facing this issue?
Could you please tell me which version of this package are you using?
Thanks

**Comment by prateekmedia** [comment]
u still facing this issue?
> Could you please tell me which version of this package are you using?
> Thanks

Sorry to say, I switched to other bottom bar, but it was not working when I was writing this issue, I have also provided the code you can check it out, other than that it was v5.6.0 which is the latest version I was facing the issue in.

I think it was my fault back then as I did not initialized and disposed the pagecontroller, anyways thanks for your response.
