### ISSUE TITLE
bLOC pattern configuration

### ISSUE THREAD

**Issue by CharlesTheProgrammerBrown** [pedromassango/bottom_navy_bar#78]
can we have the index click function as an event in bloc pattern? Or do you just use stream builder and pagination if you want one of the views to load items from firestore

**Comment by pedromassango** [comment]
Hi @CharlesTheProgrammerBrown 
Not sure if I understood correctly, but if you want to load data of one of the pages, you should do so by using a state full widget and load the data once the widget is initialized (in the `initState()`).
